### ISSUE TITLE
Feature suggestion: accept GET parameter to pre-fill new link URL field

### ISSUE THREAD

**Issue by kfarr** [mattrossman/hmd-link#2]
Feature idea:

Ability for an app to send a user to hmd.link along with destination URL. For example, a mapping application on desktop web, formats a URL such as https://hmd.link/?url=https://xr.myapp.com/1/2/3/. User clicks and then acknowledges sending to headset with hmd.link interface. Then opens headset and opens hmd.link to access link.

**Comment by mattrossman** [comment]
Hey, just saw this. That's a good idea, I should be able to add a REST endpoint to facilitate pushing links without going through the UI. There was also some discussion about the desire for a browser extension to quickly send pages to hmd.link, this could make that possible too.

**Comment by Steveorevo** [comment]
+1 

Yes please. A simple GET parameter would be nice. The shorter the better. I'd vote for no key (since it's a given) and scratch the protocol (WebXR has so many SSL constraints anyways, and virtually all browsers are making it default. And thanks to Let'sEncrypt it's a no brainer) it's 99.99% going to be https. You've got an awesome TLD for it. So something as easy as:
```
https://hmd.link/?www.myxrapp.com/folder/ 
```
Would be ideal.

**Comment by kfarr** [comment]
Hi @mattrossman this issue came up again in the WebXR discord https://discord.com/channels/758943204715659264/805647111625375764/1001345948204683349

I agree with the suggestions from @Steveorevo - there is no key nor protocol are required to keep this as simple as possible to invoke

**Comment by Utopiah** [comment]
Indeed, I'm trying to share a WebXR link to somebody who doesn't know VR at all. That would definitely be useful for then. Just one less step.

**Comment by Utopiah** [comment]
Consider the new https://developer.oculus.com/documentation/web/web-launch/

**Comment by madjin** [comment]
Came here thinking the exact same idea, checked out the meta browser team concept and think hmd.link still offers a valuable benefit of avoiding a login page.

**Comment by mattrossman** [comment]
This feature is now live.

You can put a URL (with or without protocol) as a search value e.g. `hmd.link/?example.com`

I also added a redirect rule so you can use `hmd.link/` without the `?` character for URLs that include a protocol, e.g. `hmd.link/https://example.com`. This is a little easier for me to remember, it's similar the shortcut used by https://glitch.new/ and https://stackblitz.com for importing GitHub repos (the idea being if you are already on some page, just prepend hmd.link to your URL bar)
